#ifndef WEB_PAGE_H
#define WEB_PAGE_H

static const char WEB_PAGE[] =
"<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
"<title>UPFS Desktop</title>\n"
"<style>\n"
"*{margin:0;padding:0;box-sizing:border-box}\n"

/* ---- Theme variables ---- */
":root,[data-theme=\"light\"]{\n"
"--bg:#f0f0f0;--bg2:#e8e8e8;--bg3:#ddd;--bg4:#ccc;\n"
"--fg:#222;--fg2:#666;--accent:#0071e3;--green:#34c759;--red:#ff3b30;--yellow:#ffcc00;\n"
"--border:rgba(0,0,0,.15);--font:-apple-system,BlinkMacSystemFont,'SF Pro Text','Helvetica Neue',sans-serif;\n"
"--mono:'SF Mono',Monaco,'Cascadia Code',Consolas,monospace;\n"
"--wallpaper:linear-gradient(115deg,#afc1d6 0%,#b9d6df 45%,#cef9f2 100%);\n"
"--wbg:rgba(236,236,236,.92);--wbar:rgba(228,228,228,.95);--glass:rgba(255,255,255,.72);\n"
"--shadow:0 8px 32px rgba(0,0,0,.18),0 2px 8px rgba(0,0,0,.08);\n"
"--dock-bg:rgba(255,255,255,.55)}\n"
"[data-theme=\"dark\"]{\n"
"--bg:#1e1e1e;--bg2:#2a2a2a;--bg3:#333;--bg4:#444;\n"
"--fg:#e8e8e8;--fg2:#999;--accent:#0a84ff;--green:#30d158;--red:#ff453a;--yellow:#ffd60a;\n"
"--border:rgba(255,255,255,.12);--font:-apple-system,BlinkMacSystemFont,'SF Pro Text','Helvetica Neue',sans-serif;\n"
"--mono:'SF Mono',Monaco,'Cascadia Code',Consolas,monospace;\n"
"--wallpaper:linear-gradient(115deg,#7f92a8 0%,#8fa8b7 45%,#a8d7d0 100%);\n"
"--wbg:rgba(38,38,38,.92);--wbar:rgba(48,48,48,.95);--glass:rgba(40,40,40,.72);\n"
"--shadow:0 8px 32px rgba(0,0,0,.5),0 2px 8px rgba(0,0,0,.3);\n"
"--dock-bg:rgba(50,50,50,.55)}\n"

"html,body{height:100%;overflow:hidden;font-family:var(--font);font-size:13px;color:var(--fg);user-select:none}\n"

/* ---- Menu Bar ---- */
"#menubar{height:28px;display:flex;align-items:center;padding:0 12px;\n"
"background:var(--wbar);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);\n"
"border-bottom:1px solid var(--border);position:relative;z-index:9999;\n"
"font-size:13px;font-weight:500}\n"
"#menubar .logo{font-weight:700;margin-right:16px;font-size:14px;color:var(--accent)}\n"
"#menubar .appname{color:var(--fg);font-weight:600;margin-right:20px}\n"
"#menubar .mitem{color:var(--fg2);margin-right:14px;cursor:pointer;font-size:12px}\n"
"#menubar .mitem:hover{color:var(--fg)}\n"
"#menubar .spacer{flex:1}\n"
"#menubar .right{display:flex;align-items:center;gap:10px;font-size:12px;color:var(--fg2)}\n"
"#menubar .dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:3px;vertical-align:middle}\n"
".dot.on{background:var(--green)}.dot.off{background:var(--red)}\n"
"#menubar .clock{font-variant-numeric:tabular-nums}\n"
"#themeBtn{background:none;border:none;color:var(--fg2);cursor:pointer;font-size:14px;padding:0 2px}\n"
"#themeBtn:hover{color:var(--fg)}\n"

/* ---- Desktop ---- */
"#desktop{position:absolute;top:28px;left:0;right:0;bottom:0;background:var(--wallpaper);overflow:hidden}\n"

/* ---- Window ---- */
".window{position:absolute;background:var(--wbg);border-radius:10px;box-shadow:var(--shadow);\n"
"display:flex;flex-direction:column;min-width:320px;min-height:200px;overflow:hidden;\n"
"backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid var(--border);\n"
"transition:opacity .15s,transform .15s;resize:both}\n"
".window.hidden{display:none}\n"
".window.minimized{opacity:0;transform:scale(.5) translateY(100px);pointer-events:none}\n"
".wbar{height:38px;display:flex;align-items:center;padding:0 12px;background:var(--wbar);\n"
"border-bottom:1px solid var(--border);cursor:default;flex-shrink:0;border-radius:10px 10px 0 0;position:relative}\n"
".wbar:after{content:'';width:56px;flex:0 0 56px}\n"
".wbar .lights{display:flex;gap:8px;margin-right:12px}\n"
".wbar .lights span{width:12px;height:12px;border-radius:50%;cursor:pointer;position:relative;\n"
"display:flex;align-items:center;justify-content:center;font-size:8px;color:transparent}\n"
".wbar .lights span:hover{color:rgba(0,0,0,.5)}\n"
".wbar .lights .lc{background:#ff5f57}\n"
".wbar .lights .lm{background:#febc2e}\n"
".wbar .lights .lg{background:#28c840}\n"
".wbar .wtitle{position:absolute;left:50%;transform:translateX(-50%);text-align:center;\n"
"font-size:13px;font-weight:600;color:var(--fg);max-width:60%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;pointer-events:none}\n"
".wbody{flex:1;display:flex;flex-direction:column;overflow:hidden;position:relative}\n"

/* ---- Window: Terminal ---- */
"#termtabs{display:flex;background:var(--bg2);border-bottom:1px solid var(--border);flex-shrink:0;overflow-x:auto;padding:4px 6px;gap:4px}\n"
".ttab{padding:3px 10px;cursor:pointer;color:var(--fg2);font-size:12px;white-space:nowrap;display:flex;align-items:center;border-radius:5px;font-family:var(--mono)}\n"
".ttab.on{background:var(--bg);color:var(--fg);font-weight:600}\n"
".ttab:hover:not(.on){background:var(--bg3)}\n"
".ttab .tx{margin-left:6px;font-size:13px;color:var(--fg2);cursor:pointer;line-height:1}\n"
".ttab .tx:hover{color:var(--red)}\n"
"#tadd{padding:3px 10px;cursor:pointer;color:var(--fg2);font-size:14px;background:none;border:none;border-radius:5px}\n"
"#tadd:hover{color:var(--fg);background:var(--bg3)}\n"
"#termbox{flex:1;position:relative;overflow:hidden}\n"
".term{position:absolute;top:0;left:0;right:0;bottom:0;padding:8px 10px;overflow-y:auto;\n"
"white-space:pre-wrap;word-break:break-all;font-size:13px;line-height:1.45;\n"
"display:none;background:var(--bg);color:var(--fg);font-family:var(--mono);user-select:text;-webkit-user-select:text}\n"
".term.on{display:block}\n"
"#inputbar{display:flex;border-top:1px solid var(--border);background:var(--bg2);flex-shrink:0}\n"
"#prompt{color:var(--green);padding:6px 0 6px 10px;font:13px var(--mono)}\n"
"#cmdinput{flex:1;background:none;border:none;color:var(--fg);font:13px var(--mono);outline:none;padding:6px 8px 6px 4px;caret-color:var(--accent);user-select:text;-webkit-user-select:text}\n"

/* ---- Window: Finder ---- */
".finder-head{display:flex;align-items:center;justify-content:space-between;padding:6px 10px;\n"
"border-bottom:1px solid var(--border);font-size:11px;color:var(--fg2);font-weight:600;text-transform:uppercase;letter-spacing:.5px;flex-shrink:0;background:var(--bg2)}\n"
".finder-head button{background:none;border:none;color:var(--fg2);cursor:pointer;font-size:13px;padding:2px 4px;border-radius:4px}\n"
".finder-head button:hover{color:var(--fg);background:var(--bg3)}\n"
"#filetree{flex:1;overflow-y:auto;padding:4px 0}\n"
".fnode{padding:3px 8px;margin:1px 6px;border-radius:6px;cursor:pointer;display:flex;align-items:center;\n"
"font-size:12px;color:var(--fg);white-space:nowrap}\n"
".fnode:hover{background:var(--accent);color:#fff}\n"
".fnode.sel{background:var(--accent);color:#fff}\n"
".fnode.expanded>.arrow{color:inherit}\n"
".fnode .icon{width:16px;text-align:center;margin-right:5px;font-size:11px;flex-shrink:0}\n"
".fnode .arrow{width:14px;text-align:center;font-size:9px;flex-shrink:0}\n"
".fnode .fname{overflow:hidden;text-overflow:ellipsis}\n"
".fnode .fsize{margin-left:auto;padding-left:8px;opacity:.7;font-size:11px}\n"

/* ---- Window: Monitor ---- */
".dcard{margin:10px;padding:12px;background:var(--bg3);border-radius:10px;border:1px solid var(--border)}\n"
".dcard h3{font-size:10px;color:var(--fg2);text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px;font-weight:600}\n"
".dcard .val{font-size:18px;font-weight:700;color:var(--fg)}\n"
".dcard .sub{font-size:11px;color:var(--fg2);margin-top:2px}\n"
".bgbar{display:flex;gap:2px;margin-top:6px}\n"
".bgbar .seg{flex:1;height:20px;border-radius:4px;position:relative;overflow:hidden;background:var(--bg4)}\n"
".bgbar .seg .fill{position:absolute;bottom:0;left:0;right:0;background:var(--accent);transition:height .3s;border-radius:4px}\n"
".bgbar .seg .lbl{position:absolute;bottom:0;left:0;right:0;text-align:center;font-size:8px;color:var(--fg2);z-index:1}\n"
".proctbl{width:100%;font-size:11px;border-collapse:collapse}\n"
".proctbl th{text-align:left;color:var(--fg2);padding:3px 4px;border-bottom:1px solid var(--border);font-weight:600}\n"
".proctbl td{padding:3px 4px;color:var(--fg)}\n"
".memgrid{display:grid;grid-template-columns:repeat(32,1fr);gap:1px}\n"
".memcell{width:100%;aspect-ratio:1;border-radius:1px}\n"

/* ---- Window: TextEdit ---- */
".edit-toolbar{display:flex;align-items:center;gap:6px;padding:4px 10px;border-bottom:1px solid var(--border);background:var(--bg2);flex-shrink:0}\n"
".edit-toolbar .epath{flex:1;background:var(--bg);border:1px solid var(--border);border-radius:5px;padding:3px 8px;\n"
"font:12px var(--mono);color:var(--fg);outline:none;min-width:0;user-select:text;-webkit-user-select:text}\n"
".edit-toolbar .epath:focus{border-color:var(--accent)}\n"
".edit-toolbar .ebtn{padding:3px 10px;border-radius:5px;border:1px solid var(--border);background:var(--bg);\n"
"color:var(--fg);cursor:pointer;font-size:11px;font-weight:600;white-space:nowrap}\n"
".edit-toolbar .ebtn:hover{background:var(--bg3)}\n"
".edit-toolbar .ebtn.save{background:var(--accent);color:#fff;border-color:var(--accent)}\n"
".edit-toolbar .ebtn.save:hover{opacity:.85}\n"
"#editor{flex:1;width:100%;background:var(--bg);color:var(--fg);border:none;resize:none;outline:none;\n"
"font:13px/1.5 var(--mono);padding:8px 10px;tab-size:4;-moz-tab-size:4;user-select:text;-webkit-user-select:text}\n"
".edit-status{display:flex;align-items:center;justify-content:space-between;padding:2px 10px;\n"
"border-top:1px solid var(--border);background:var(--bg2);font-size:11px;color:var(--fg2);flex-shrink:0}\n"
".edit-status .dirty{color:var(--yellow);font-weight:700}\n"

/* ---- Dock ---- */
"#dock{position:absolute;bottom:8px;left:50%;transform:translateX(-50%);display:flex;align-items:flex-end;\n"
"padding:4px 8px;gap:2px;border-radius:18px;z-index:9998;\n"
"background:var(--dock-bg);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);\n"
"border:1px solid var(--border)}\n"
".dock-icon{width:56px;height:56px;border-radius:14px;display:flex;flex-direction:column;\n"
"align-items:center;justify-content:center;cursor:pointer;transition:transform .15s,filter .15s;\n"
"position:relative;font-size:28px}\n"
".dock-icon:hover{transform:scale(1.25) translateY(-8px)}\n"
".dock-icon:hover .app-ico{filter:brightness(1.06)}\n"
".dock-icon .dlabel{font-size:9px;color:var(--fg2);margin-top:1px;font-family:var(--font);font-weight:500}\n"
".dock-icon .ddot{width:4px;height:4px;border-radius:50%;background:var(--fg2);position:absolute;bottom:-2px;\n"
"opacity:0;transition:opacity .2s}\n"
".dock-icon .ddot.active{opacity:1}\n"
".app-ico{width:42px;height:42px;border-radius:11px;display:flex;align-items:center;justify-content:center;\n"
"font-weight:700;box-shadow:inset 0 1px 0 rgba(255,255,255,.35),0 3px 10px rgba(0,0,0,.22)}\n"
".app-finder{background:linear-gradient(180deg,#8fc6ff,#4da3ff);color:#fff;font-size:18px}\n"
".app-terminal{background:linear-gradient(180deg,#3b3b3b,#202020);color:#8bf18b;font-family:var(--mono);font-size:13px}\n"
".app-monitor{background:linear-gradient(180deg,#6a7cff,#4957d8);color:#fff;font-size:18px}\n"
".app-editor{background:linear-gradient(180deg,#ffffff,#e7ecf4);color:#394b6a;font-size:18px;border:1px solid rgba(0,0,0,.12)}\n"
".dock-sep{width:1px;height:36px;background:var(--border);margin:0 6px;align-self:center}\n"

/* ---- Context menu ---- */
"#ctxmenu{position:fixed;background:var(--glass);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);\n"
"border:1px solid var(--border);border-radius:8px;padding:4px 0;min-width:180px;z-index:99999;display:none;\n"
"box-shadow:0 6px 20px rgba(0,0,0,.2)}\n"
"#ctxmenu .item{padding:4px 12px;margin:1px 4px;border-radius:4px;font-size:12px;cursor:pointer;color:var(--fg)}\n"
"#ctxmenu .item:hover{background:var(--accent);color:#fff}\n"
"#ctxmenu .sep{height:1px;background:var(--border);margin:3px 0}\n"

/* ---- Modal ---- */
".modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.4);z-index:100000;\n"
"display:flex;align-items:center;justify-content:center}\n"
".modal{background:var(--wbg);backdrop-filter:blur(20px);border:1px solid var(--border);\n"
"border-radius:12px;padding:24px;min-width:300px;box-shadow:0 8px 30px rgba(0,0,0,.2)}\n"
".modal h3{font-size:15px;margin-bottom:14px;color:var(--fg);font-weight:600}\n"
".modal input{width:100%;padding:7px 10px;background:var(--bg);border:1px solid var(--border);\n"
"border-radius:6px;color:var(--fg);font:13px var(--mono);outline:none;margin-bottom:12px}\n"
".modal input:focus{border-color:var(--accent)}\n"
".modal .btns{display:flex;gap:8px;justify-content:flex-end}\n"
".modal .btn{padding:6px 14px;border-radius:6px;border:1px solid var(--border);background:var(--bg);\n"
"color:var(--fg);cursor:pointer;font-size:12px}\n"
".modal .btn.primary{background:var(--accent);color:#fff;border-color:var(--accent)}\n"

/* ---- Scrollbar ---- */
"::-webkit-scrollbar{width:6px;height:6px}\n"
"::-webkit-scrollbar-track{background:transparent}\n"
"::-webkit-scrollbar-thumb{background:var(--bg4);border-radius:3px}\n"
"::-webkit-scrollbar-thumb:hover{background:var(--fg2)}\n"
".boot-screen{position:fixed;inset:0;z-index:1000000;display:flex;align-items:center;justify-content:center;\n"
"background:linear-gradient(115deg,#afc1d6 0%,#b9d6df 45%,#cef9f2 100%);\n"
"transition:opacity .8s ease,visibility .8s ease}\n"
".boot-screen.hide{opacity:0;visibility:hidden}\n"
".boot-card{padding:0;border-radius:0;background:transparent;box-shadow:none;\n"
"display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;color:#655a7c;width:100%}\n"
".boot-logo{font-size:30px;font-weight:800;letter-spacing:.5px;color:#655a7c}\n"
".boot-quote{font-size:50px;line-height:1.2;font-weight:500;letter-spacing:.2px;color:#655a7c;\n"
"font-family:'Snell Roundhand','Apple Chancery','Zapfino','Comic Sans MS',cursive;\n"
"white-space:nowrap;overflow:hidden;border-right:2px solid #655a7c;width:0;opacity:0;text-align:center}\n"
".boot-screen.show .boot-quote{opacity:1;animation:typing 2.2s steps(37,end) .25s forwards,blink .7s step-end infinite .25s}\n"
".boot-spinner{width:26px;height:26px;border-radius:50%;border:3px solid rgba(255,255,255,.35);\n"
"border-top-color:#655a7c;animation:bootspin 1s linear infinite}\n"
"@keyframes bootspin{to{transform:rotate(360deg)}}\n"
"@keyframes typing{from{width:0}to{width:37ch}}\n"
"@keyframes blink{50%{border-color:transparent}}\n"

"</style>\n"

/* ---- Early theme init ---- */
"<script>(function(){var t=localStorage.getItem('upfs-theme');\n"
"if(t!=='dark'&&t!=='light'){try{t=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'}catch(e){t='light'}}\n"
"document.documentElement.setAttribute('data-theme',t)})()</script>\n"
"</head>\n"

"<body>\n"
"<div id=\"boot-screen\" class=\"boot-screen\">\n"
"<div class=\"boot-card\">\n"
"<div class=\"boot-logo\">UPFS Desktop</div>\n"
"<div class=\"boot-quote\">Understand Problems, Find Solutions.</div>\n"
"<div class=\"boot-spinner\"></div>\n"
"</div>\n"
"</div>\n"

/* ======== Menu Bar ======== */
"<div id=\"menubar\">\n"
"<span class=\"logo\">UPFS</span>\n"
"<span class=\"appname\" id=\"mb-app\">Desktop</span>\n"
"<span class=\"mitem\" onclick=\"openWin('terminal')\">Terminal</span>\n"
"<span class=\"mitem\" onclick=\"openWin('finder')\">Finder</span>\n"
"<span class=\"mitem\" onclick=\"openWin('monitor')\">Monitor</span>\n"
"<span class=\"mitem\" onclick=\"openWin('editor')\">TextEdit</span>\n"
"<span class=\"spacer\"></span>\n"
"<span class=\"right\">\n"
"<span><span class=\"dot off\" id=\"sdot\"></span><span id=\"stxt\">Connecting</span></span>\n"
"<button id=\"themeBtn\" onclick=\"toggleTheme()\" title=\"Toggle theme\">&#9788;</button>\n"
"<span class=\"clock\" id=\"clock\"></span>\n"
"</span>\n"
"</div>\n"

/* ======== Desktop ======== */
"<div id=\"desktop\">\n"

/* ---- Window: Terminal ---- */
"<div class=\"window\" id=\"win-terminal\" style=\"width:780px;height:480px;left:120px;top:40px;z-index:10\">\n"
"<div class=\"wbar\" onmousedown=\"dragStart(event,'win-terminal')\">\n"
"<div class=\"lights\">\n"
"<span class=\"lc\" onclick=\"closeWin('terminal')\">&times;</span>\n"
"<span class=\"lm\" onclick=\"minimizeWin('terminal')\">&minus;</span>\n"
"<span class=\"lg\" onclick=\"maximizeWin('terminal')\">&plus;</span>\n"
"</div>\n"
"<div class=\"wtitle\">Terminal</div>\n"
"</div>\n"
"<div class=\"wbody\">\n"
"<div id=\"termtabs\"><button id=\"tadd\" onclick=\"newTerm()\">+</button></div>\n"
"<div id=\"termbox\"></div>\n"
"<div id=\"inputbar\"><span id=\"prompt\">$ </span><input id=\"cmdinput\" autocomplete=\"off\" spellcheck=\"false\"></div>\n"
"</div>\n"
"</div>\n"

/* ---- Window: Finder ---- */
"<div class=\"window hidden\" id=\"win-finder\" style=\"width:380px;height:460px;left:60px;top:60px;z-index:9\">\n"
"<div class=\"wbar\" onmousedown=\"dragStart(event,'win-finder')\">\n"
"<div class=\"lights\">\n"
"<span class=\"lc\" onclick=\"closeWin('finder')\">&times;</span>\n"
"<span class=\"lm\" onclick=\"minimizeWin('finder')\">&minus;</span>\n"
"<span class=\"lg\" onclick=\"maximizeWin('finder')\">&plus;</span>\n"
"</div>\n"
"<div class=\"wtitle\">Finder</div>\n"
"</div>\n"
"<div class=\"wbody\">\n"
"<div class=\"finder-head\"><span>Files</span><span>\n"
"<button onclick=\"apiSend({cmd:'mkdir',path:promptPath('New directory path:')})\" title=\"New Dir\">+D</button>\n"
"<button onclick=\"apiSend({cmd:'create',path:promptPath('New file path:')})\" title=\"New File\">+F</button>\n"
"<button onclick=\"refreshTree()\" title=\"Refresh\">&#x21bb;</button>\n"
"</span></div>\n"
"<div id=\"filetree\"></div>\n"
"</div>\n"
"</div>\n"

/* ---- Window: Monitor ---- */
"<div class=\"window hidden\" id=\"win-monitor\" style=\"width:360px;height:520px;right:40px;top:60px;z-index:8\">\n"
"<div class=\"wbar\" onmousedown=\"dragStart(event,'win-monitor')\">\n"
"<div class=\"lights\">\n"
"<span class=\"lc\" onclick=\"closeWin('monitor')\">&times;</span>\n"
"<span class=\"lm\" onclick=\"minimizeWin('monitor')\">&minus;</span>\n"
"<span class=\"lg\" onclick=\"maximizeWin('monitor')\">&plus;</span>\n"
"</div>\n"
"<div class=\"wtitle\">Activity Monitor</div>\n"
"</div>\n"
"<div class=\"wbody\" style=\"overflow-y:auto\">\n"
"<div class=\"dcard\"><h3>Filesystem</h3><div class=\"val\" id=\"d-fs\">--</div><div class=\"sub\" id=\"d-fs-sub\"></div></div>\n"
"<div class=\"dcard\"><h3>Block Groups</h3><div class=\"bgbar\" id=\"d-bgbar\"></div></div>\n"
"<div class=\"dcard\"><h3>Processes</h3><table class=\"proctbl\"><thead><tr><th>PID</th><th>Name</th><th>State</th></tr></thead><tbody id=\"d-procs\"></tbody></table></div>\n"
"<div class=\"dcard\"><h3>Memory</h3><div class=\"sub\" id=\"d-meminfo\"></div><div class=\"memgrid\" id=\"d-memgrid\"></div></div>\n"
"</div>\n"
"</div>\n"

/* ---- Window: TextEdit ---- */
"<div class=\"window hidden\" id=\"win-editor\" style=\"width:640px;height:480px;left:180px;top:80px;z-index:7\">\n"
"<div class=\"wbar\" onmousedown=\"dragStart(event,'win-editor')\">\n"
"<div class=\"lights\">\n"
"<span class=\"lc\" onclick=\"closeWin('editor')\">&times;</span>\n"
"<span class=\"lm\" onclick=\"minimizeWin('editor')\">&minus;</span>\n"
"<span class=\"lg\" onclick=\"maximizeWin('editor')\">&plus;</span>\n"
"</div>\n"
"<div class=\"wtitle\" id=\"editor-title\">TextEdit</div>\n"
"</div>\n"
"<div class=\"wbody\">\n"
"<div class=\"edit-toolbar\">\n"
"<input class=\"epath\" id=\"edit-path\" placeholder=\"/path/to/file\" spellcheck=\"false\">\n"
"<button class=\"ebtn\" onclick=\"editorOpen()\">Open</button>\n"
"<button class=\"ebtn save\" onclick=\"editorSave()\">Save</button>\n"
"<button class=\"ebtn\" onclick=\"editorNew()\">New</button>\n"
"</div>\n"
"<textarea id=\"editor\" spellcheck=\"false\"></textarea>\n"
"<div class=\"edit-status\"><span id=\"edit-dirty\"></span><span id=\"edit-info\">Ready</span></div>\n"
"</div>\n"
"</div>\n"

"</div>\n"

/* ======== Dock ======== */
"<div id=\"dock\">\n"
"<div class=\"dock-icon\" onclick=\"openWin('finder')\" title=\"Finder\">\n"
"<span class=\"app-ico app-finder\">F</span><div class=\"ddot\" id=\"dd-finder\"></div></div>\n"
"<div class=\"dock-icon\" onclick=\"openWin('terminal')\" title=\"Terminal\">\n"
"<span class=\"app-ico app-terminal\">&gt;_</span><div class=\"ddot\" id=\"dd-terminal\"></div></div>\n"
"<div class=\"dock-icon\" onclick=\"openWin('monitor')\" title=\"Activity Monitor\">\n"
"<span class=\"app-ico app-monitor\">M</span><div class=\"ddot\" id=\"dd-monitor\"></div></div>\n"
"<div class=\"dock-icon\" onclick=\"openWin('editor')\" title=\"TextEdit\">\n"
"<span class=\"app-ico app-editor\">T</span><div class=\"ddot\" id=\"dd-editor\"></div></div>\n"
"</div>\n"

/* ======== Context Menu ======== */
"<div id=\"ctxmenu\"></div>\n"

/* ======== JavaScript ======== */
"<script>\n"
"'use strict';\n"

/* ---- Globals ---- */
"var terms=[],curTerm=0,MAX_TERMS=8;\n"
"var apiWs=null,apiOk=false,apiCallbacks={},apiReqId=0;\n"
"var selPath='/',topZ=10;\n"

/* ============================================================ */
/* ---- Theme ---- */
/* ============================================================ */
"function applyTheme(t){\n"
"document.documentElement.setAttribute('data-theme',t);\n"
"try{localStorage.setItem('upfs-theme',t)}catch(e){}\n"
"var b=document.getElementById('themeBtn');\n"
"if(b)b.innerHTML=t==='dark'?'&#9790;':'&#9788;'}\n"
"function toggleTheme(){\n"
"var c=document.documentElement.getAttribute('data-theme')||'light';\n"
"applyTheme(c==='dark'?'light':'dark')}\n"
"function initTheme(){\n"
"var t=document.documentElement.getAttribute('data-theme')||'light';\n"
"applyTheme(t)}\n"
"function startBootScreen(){\n"
"var b=document.getElementById('boot-screen');\n"
"if(!b)return;\n"
"b.classList.add('show');\n"
"setTimeout(function(){b.classList.add('hide')},3400)}\n"

/* ---- Clock ---- */
"function tickClock(){\n"
"var d=new Date(),h=d.getHours(),m=d.getMinutes();\n"
"document.getElementById('clock').textContent=\n"
"(h<10?'0':'')+h+':'+(m<10?'0':'')+m}\n"
"setInterval(tickClock,10000);tickClock();\n"

/* ============================================================ */
/* ---- Window Manager ---- */
/* ============================================================ */
"function winEl(id){return document.getElementById('win-'+id)}\n"

"function openWin(id){\n"
"var w=winEl(id);if(!w)return;\n"
"w.classList.remove('hidden','minimized');\n"
"focusWin(id);updDock()}\n"

"function closeWin(id){\n"
"var w=winEl(id);if(w)w.classList.add('hidden');\n"
"updDock();updMenuApp()}\n"

"function minimizeWin(id){\n"
"var w=winEl(id);if(w)w.classList.add('minimized');\n"
"updDock();updMenuApp()}\n"

"function maximizeWin(id){\n"
"var w=winEl(id);if(!w)return;\n"
"var desk=document.getElementById('desktop');\n"
"if(w.getAttribute('data-max')==='1'){\n"
"w.style.left=w.getAttribute('data-ox')+'px';w.style.top=w.getAttribute('data-oy')+'px';\n"
"w.style.width=w.getAttribute('data-ow')+'px';w.style.height=w.getAttribute('data-oh')+'px';\n"
"w.removeAttribute('data-max');\n"
"}else{\n"
"w.setAttribute('data-ox',w.offsetLeft);w.setAttribute('data-oy',w.offsetTop);\n"
"w.setAttribute('data-ow',w.offsetWidth);w.setAttribute('data-oh',w.offsetHeight);\n"
"w.style.left='0';w.style.top='0';\n"
"w.style.width=desk.offsetWidth+'px';w.style.height=desk.offsetHeight+'px';\n"
"w.setAttribute('data-max','1');\n"
"}focusWin(id)}\n"

"function focusWin(id){\n"
"var w=winEl(id);if(!w)return;\n"
"topZ++;w.style.zIndex=topZ;\n"
"document.querySelectorAll('.window').forEach(function(x){x.classList.remove('focused')});\n"
"w.classList.add('focused');\n"
"updMenuApp();\n"
"if(id==='terminal'){var ci=document.getElementById('cmdinput');if(ci)ci.focus()}}\n"

"function updMenuApp(){\n"
"var best=null,bestZ=0;\n"
"document.querySelectorAll('.window').forEach(function(w){\n"
"if(w.classList.contains('hidden')||w.classList.contains('minimized'))return;\n"
"var z=parseInt(w.style.zIndex)||0;if(z>bestZ){bestZ=z;best=w}});\n"
"var t=best?best.querySelector('.wtitle').textContent:'Desktop';\n"
"document.getElementById('mb-app').textContent=t}\n"

"function updDock(){\n"
"['terminal','finder','monitor','editor'].forEach(function(id){\n"
"var w=winEl(id);var dd=document.getElementById('dd-'+id);\n"
"if(dd)dd.classList.toggle('active',w&&!w.classList.contains('hidden'))})}\n"

/* ---- Drag ---- */
"var dragWin=null,dragOx=0,dragOy=0;\n"
"function dragStart(e,wid){\n"
"if(e.target.closest('.lights'))return;\n"
"var w=document.getElementById(wid);if(!w)return;\n"
"dragWin=w;dragOx=e.clientX-w.offsetLeft;dragOy=e.clientY-w.offsetTop;\n"
"var id=wid.replace('win-','');focusWin(id);\n"
"e.preventDefault()}\n"
"document.addEventListener('mousemove',function(e){\n"
"if(!dragWin)return;\n"
"dragWin.style.left=Math.max(0,e.clientX-dragOx)+'px';\n"
"dragWin.style.top=Math.max(0,e.clientY-dragOy)+'px';\n"
"dragWin.removeAttribute('data-max')});\n"
"document.addEventListener('mouseup',function(){dragWin=null});\n"

/* ---- Click to focus ---- */
"document.addEventListener('mousedown',function(e){\n"
"var w=e.target.closest('.window');if(!w)return;\n"
"var id=w.id.replace('win-','');focusWin(id)});\n"

/* ============================================================ */
/* ---- ANSI Parser ---- */
/* ============================================================ */
"function H(s){\n"
"var o='',i=0,fg=null,bg=null,bd=false,dm=false,sp=false;\n"
"function sc(){var a=[];\n"
"if(bd)a.push('font-weight:bold');\n"
"if(dm)a.push('opacity:.6');\n"
"if(fg)a.push('color:rgb('+fg.join(',')+')');\n"
"if(bg)a.push('background:rgb('+bg.join(',')+')');\n"
"return a.join(';')}\n"
"while(i<s.length){\n"
"if(s.charCodeAt(i)===27&&s[i+1]==='['){\n"
"var j=i+2;while(j<s.length&&!((s.charCodeAt(j)>=64&&s.charCodeAt(j)<=126)))j++;\n"
"if(j>=s.length)break;\n"
"var ch=s[j];\n"
"if(ch==='m'){\n"
"var t=s.substring(i+2,j).split(';'),k=0;\n"
"while(k<t.length){var v=parseInt(t[k])||0;\n"
"if(v===0){fg=null;bg=null;bd=false;dm=false;k++}\n"
"else if(v===1){bd=true;k++}\n"
"else if(v===2){dm=true;k++}\n"
"else if(v>=30&&v<=37){var c=v-30;fg=[[0,0,0],[205,49,49],[13,188,121],[229,229,16],[36,114,200],[188,63,188],[17,168,205],[204,204,204]][c];k++}\n"
"else if(v>=90&&v<=97){var c=v-90;fg=[[102,102,102],[241,76,76],[35,209,139],[245,245,67],[59,142,234],[214,112,214],[41,184,219],[242,242,242]][c];k++}\n"
"else if(v===38&&k+4<t.length&&parseInt(t[k+1])===2){fg=[parseInt(t[k+2])||0,parseInt(t[k+3])||0,parseInt(t[k+4])||0];k+=5}\n"
"else if(v===48&&k+4<t.length&&parseInt(t[k+1])===2){bg=[parseInt(t[k+2])||0,parseInt(t[k+3])||0,parseInt(t[k+4])||0];k+=5}\n"
"else k++}\n"
"var nc=sc();\n"
"if(nc!==sc.last){if(sp){o+='</span>';sp=false}\n"
"if(nc){o+='<span style=\"'+nc+'\">';sp=true}\n"
"sc.last=nc}\n"
"}else if(ch==='J'||ch==='K'||ch==='H'||ch==='A'||ch==='B'||ch==='C'||ch==='D'){}\n"
"i=j+1;\n"
"}else{\n"
"var c=s[i];\n"
"if(c==='&')o+='&amp;';else if(c==='<')o+='&lt;';else if(c==='>')o+='&gt;';else if(c==='\\r'){}else o+=c;\n"
"i++}}\n"
"if(sp)o+='</span>';return o}\n"
"H.last='';\n"

/* ============================================================ */
/* ---- WebSocket Terminal ---- */
/* ============================================================ */
"function newTerm(){\n"
"if(terms.length>=MAX_TERMS)return;\n"
"var idx=terms.length;\n"
"var ws=new WebSocket('ws://'+location.host+'/ws/'+idx);\n"
"ws.binaryType='arraybuffer';\n"
"var el=document.createElement('div');el.className='term';\n"
"var t={id:idx,ws:ws,el:el,ok:false};\n"
"ws.onopen=function(){t.ok=true;updStatus()};\n"
"ws.onmessage=function(e){\n"
"var s=typeof e.data==='string'?e.data:new TextDecoder().decode(e.data);\n"
"el.innerHTML+=H(s);el.scrollTop=el.scrollHeight};\n"
"ws.onclose=function(){t.ok=false;el.innerHTML+='\\n<span style=\"color:var(--fg2)\">-- session closed --</span>\\n';updStatus()};\n"
"terms.push(t);document.getElementById('termbox').appendChild(el);\n"
"mkTab(idx);if(terms.length===1)selTerm(0)}\n"

"function mkTab(i){\n"
"var b=document.createElement('span');b.className='ttab';b.setAttribute('data-i',i);\n"
"var s=document.createElement('span');s.textContent='Shell '+(i+1);\n"
"s.onclick=function(){selTerm(i)};\n"
"b.appendChild(s);\n"
"var x=document.createElement('span');x.className='tx';x.innerHTML='&times;';\n"
"x.onclick=function(e){e.stopPropagation();closeTerm(i)};\n"
"b.appendChild(x);\n"
"document.getElementById('termtabs').insertBefore(b,document.getElementById('tadd'))}\n"

"function selTerm(i){\n"
"curTerm=i;\n"
"document.querySelectorAll('.ttab').forEach(function(t,j){t.classList.toggle('on',j===i)});\n"
"document.querySelectorAll('.term').forEach(function(t,j){t.classList.toggle('on',j===i)});\n"
"document.getElementById('cmdinput').focus()}\n"

"function closeTerm(i){\n"
"if(terms.length<=1)return;\n"
"var t=terms[i];if(t.ws.readyState===1)t.ws.close();\n"
"t.el.remove();\n"
"document.querySelectorAll('.ttab')[i].remove();\n"
"terms.splice(i,1);\n"
"document.querySelectorAll('.ttab').forEach(function(tb,j){\n"
"tb.querySelector('span').textContent='Shell '+(j+1);\n"
"tb.querySelector('span').onclick=(function(k){return function(){selTerm(k)}})(j);\n"
"tb.querySelector('.tx').onclick=(function(k){return function(e){e.stopPropagation();closeTerm(k)}})(j)});\n"
"if(curTerm>=terms.length)curTerm=terms.length-1;selTerm(curTerm)}\n"

"document.getElementById('cmdinput').onkeydown=function(e){\n"
"if(e.key==='Enter'){\n"
"var v=this.value;this.value='';\n"
"var t=terms[curTerm];\n"
"if(t&&t.ok)t.ws.send(v+'\\n')}};\n"

/* ============================================================ */
/* ---- API WebSocket ---- */
/* ============================================================ */
"function apiConnect(){\n"
"apiWs=new WebSocket('ws://'+location.host+'/api');\n"
"apiWs.onopen=function(){apiOk=true;updStatus();refreshTree();refreshDash()};\n"
"apiWs.onmessage=function(e){\n"
"try{var d=JSON.parse(e.data);if(d._cb){var fn=apiCallbacks[d._cb];if(fn){delete apiCallbacks[d._cb];fn(d)}}}catch(ex){}};\n"
"apiWs.onclose=function(){apiOk=false;updStatus();apiCallbacks={};setTimeout(apiConnect,2000)};\n"
"apiWs.onerror=function(){}}\n"

"function apiSend(obj,cb){\n"
"if(!obj||!obj.cmd)return;\n"
"if(!obj.path&&obj.cmd!=='debug')return;\n"
"if(!apiOk){setTimeout(function(){apiSend(obj,cb)},500);return}\n"
"var id=++apiReqId;obj._cb=id;\n"
"apiCallbacks[id]=cb||function(){};\n"
"apiWs.send(JSON.stringify(obj))}\n"

/* ---- Status ---- */
"function updStatus(){\n"
"var ok=apiOk;var dot=document.getElementById('sdot');\n"
"var txt=document.getElementById('stxt');\n"
"dot.className='dot '+(ok?'on':'off');\n"
"txt.textContent=ok?'Connected':'Disconnected'}\n"

/* ============================================================ */
/* ---- File Browser (Finder) ---- */
/* ============================================================ */
"function promptPath(msg){var p=prompt(msg);return p||''}\n"

"function refreshTree(){\n"
"var el=document.getElementById('filetree');\n"
"apiSend({cmd:'ls',path:'/'},function(d){\n"
"if(!d.ok){el.innerHTML='<div class=\"fnode\" style=\"padding:12px;color:var(--fg2)\">'+(d.error==='not mounted'?'Not mounted: run mount in Terminal':'')+(d.error||'ls failed')+'</div>';return}\n"
"if(!d.entries){el.innerHTML='<div class=\"fnode\" style=\"padding:12px;color:var(--fg2)\">(empty)</div>';return}\n"
"el.innerHTML='';\n"
"renderDir('/',d.entries,el,0)})}\n"

"function collapseDir(node){\n"
"var depth=parseInt(node.getAttribute('data-depth')||'0',10);\n"
"var s=node.nextSibling;\n"
"while(s&&s.classList&&s.classList.contains('fnode')){\n"
"var cd=parseInt(s.getAttribute('data-depth')||'0',10);\n"
"if(cd<=depth)break;\n"
"var nx=s.nextSibling;s.remove();s=nx}\n"
"node.classList.remove('expanded');\n"
"var ar=node.querySelector('.arrow');if(ar)ar.textContent='\\u25B6'}\n"

"function expandDir(node,path,depth){\n"
"if(node.classList.contains('expanded'))return;\n"
"var arrow=node.querySelector('.arrow');\n"
"node.classList.add('expanded');\n"
"if(arrow)arrow.textContent='\\u25BC';\n"
"apiSend({cmd:'ls',path:path},function(d){\n"
"if(!d.ok||!d.entries||!node.classList.contains('expanded'))return;\n"
"var tmp=document.createElement('div');\n"
"renderDir(path,d.entries,tmp,depth+1);\n"
"var ref=node.nextSibling;\n"
"while(tmp.firstChild)node.parentNode.insertBefore(tmp.firstChild,ref)})}\n"

"function renderDir(path,entries,parent,depth){\n"
"entries.sort(function(a,b){if(a.type==='d'&&b.type!=='d')return -1;if(a.type!=='d'&&b.type==='d')return 1;return a.name<b.name?-1:1});\n"
"entries.forEach(function(e){\n"
"if(e.name==='.'||e.name==='..')return;\n"
"var fp=(path==='/'?'/':path+'/')+e.name;\n"
"var n=document.createElement('div');n.className='fnode';\n"
"n.style.paddingLeft=(8+depth*16)+'px';\n"
"n.setAttribute('data-path',fp);n.setAttribute('data-type',e.type);\n"
"n.setAttribute('data-depth',String(depth));\n"
"var arrow=document.createElement('span');arrow.className='arrow';\n"
"if(e.type==='d')arrow.textContent='\\u25B6';else arrow.textContent=' ';\n"
"n.appendChild(arrow);\n"
"var ico=document.createElement('span');ico.className='icon';\n"
"ico.textContent=e.type==='d'?'\\uD83D\\uDCC1':'\\uD83D\\uDCC4';n.appendChild(ico);\n"
"var nm=document.createElement('span');nm.className='fname';nm.textContent=e.name;n.appendChild(nm);\n"
"if(e.type!=='d'){var sz=document.createElement('span');sz.className='fsize';sz.textContent=fmtSz(e.size);n.appendChild(sz)}\n"
"n.onclick=function(ev){ev.stopPropagation();\n"
"var wasSel=n.classList.contains('sel');\n"
"document.querySelectorAll('.fnode.sel').forEach(function(x){x.classList.remove('sel')});\n"
"n.classList.add('sel');selPath=fp;\n"
"if(e.type==='d'){\n"
"if(wasSel&&n.classList.contains('expanded'))collapseDir(n);\n"
"else if(!n.classList.contains('expanded'))expandDir(n,fp,depth)}};\n"
"if(e.type!=='d')n.ondblclick=function(){editorOpen(fp)};\n"
"n.oncontextmenu=function(ev){ev.preventDefault();ev.stopPropagation();showCtx(ev,fp,e.type)};\n"
"parent.appendChild(n)})}\n"

"function fmtSz(n){\n"
"if(n==null)return '';\n"
"if(n<1024)return n+'B';\n"
"if(n<1048576)return (n/1024).toFixed(1)+'K';\n"
"return (n/1048576).toFixed(1)+'M'}\n"

/* ---- Context Menu ---- */
"function showCtx(ev,path,type){\n"
"var m=document.getElementById('ctxmenu');m.innerHTML='';\n"
"function add(label,fn){var d=document.createElement('div');d.className='item';d.textContent=label;\n"
"d.onclick=function(){m.style.display='none';fn()};m.appendChild(d)}\n"
"function sep(){var d=document.createElement('div');d.className='sep';m.appendChild(d)}\n"
"if(type==='d'){\n"
"add('Open in Terminal',function(){var t=terms[curTerm];if(t&&t.ok)t.ws.send('cd '+path+'\\n');openWin('terminal')});\n"
"add('List contents',function(){var t=terms[curTerm];if(t&&t.ok)t.ws.send('ls '+path+'\\n');openWin('terminal')});\n"
"sep();\n"
"add('New file here...',function(){var n=prompt('File name:');if(n)apiSend({cmd:'create',path:path+'/'+n},function(){refreshTree()})});\n"
"add('New directory...',function(){var n=prompt('Dir name:');if(n)apiSend({cmd:'mkdir',path:path+'/'+n},function(){refreshTree()})});\n"
"}else{\n"
"add('Edit in TextEdit',function(){editorOpen(path)});\n"
"add('View content',function(){apiSend({cmd:'cat',path:path},function(d){if(d.data!=null)alert(d.data);else alert('Error: '+(d.error||'unknown'))})});\n"
"add('Stat',function(){apiSend({cmd:'stat',path:path},function(d){var s='';for(var k in d)if(k!=='_cb')s+=k+': '+d[k]+'\\n';alert(s)})});\n"
"}\n"
"sep();\n"
"add('Delete',function(){if(confirm('Delete '+path+'?'))apiSend({cmd:'rm',path:path},function(){refreshTree()})});\n"
"m.style.left=ev.clientX+'px';m.style.top=ev.clientY+'px';m.style.display='block'}\n"

"document.addEventListener('click',function(){document.getElementById('ctxmenu').style.display='none'});\n"

/* ---- Desktop right-click menu ---- */
"document.getElementById('desktop').addEventListener('contextmenu',function(ev){\n"
"if(ev.target.closest('.window'))return;\n"
"ev.preventDefault();\n"
"var m=document.getElementById('ctxmenu');m.innerHTML='';\n"
"function add(label,fn){var d=document.createElement('div');d.className='item';d.textContent=label;\n"
"d.onclick=function(){m.style.display='none';fn()};m.appendChild(d)}\n"
"function sep(){var d=document.createElement('div');d.className='sep';m.appendChild(d)}\n"
"var apps=[['Terminal','terminal'],['Finder','finder'],['Activity Monitor','monitor'],['TextEdit','editor']];\n"
"apps.forEach(function(a){\n"
"var w=winEl(a[1]);var vis=w&&!w.classList.contains('hidden')&&!w.classList.contains('minimized');\n"
"add((vis?'Close ':'Open ')+a[0],function(){vis?closeWin(a[1]):openWin(a[1])})});\n"
"sep();\n"
"add('Toggle Theme',toggleTheme);\n"
"m.style.left=ev.clientX+'px';m.style.top=ev.clientY+'px';m.style.display='block'});\n"

/* ============================================================ */
/* ---- Dashboard (Monitor) ---- */
/* ============================================================ */
"function refreshDash(){\n"
"apiSend({cmd:'debug',type:'super'},function(d){\n"
"if(!d.ok&&d.error){document.getElementById('d-fs').textContent='Not mounted';return}\n"
"document.getElementById('d-fs').textContent=d.inodes_used+' / '+(d.inodes_total||'?')+' inodes';\n"
"document.getElementById('d-fs-sub').textContent='Blocks: '+(d.blocks_total-d.blocks_free)+'/'+d.blocks_total+' used';\n"
"if(d.bg){\n"
"var bar=document.getElementById('d-bgbar');bar.innerHTML='';\n"
"d.bg.forEach(function(g,i){\n"
"var seg=document.createElement('div');seg.className='seg';\n"
"var fill=document.createElement('div');fill.className='fill';\n"
"var pct=g.data_blocks>0?Math.round((g.data_blocks-g.free)*100/g.data_blocks):0;\n"
"fill.style.height=pct+'%';seg.appendChild(fill);\n"
"var lbl=document.createElement('div');lbl.className='lbl';lbl.textContent='G'+i;\n"
"seg.appendChild(lbl);seg.title='Group '+i+': '+(g.data_blocks-g.free)+'/'+g.data_blocks+' used';\n"
"bar.appendChild(seg)})}});\n"

"apiSend({cmd:'debug',type:'process'},function(d){\n"
"var tb=document.getElementById('d-procs');tb.innerHTML='';\n"
"if(!d.procs||d.procs.length===0){tb.innerHTML='<tr><td colspan=\"3\" style=\"color:var(--fg2)\">No processes</td></tr>';return}\n"
"d.procs.forEach(function(p){\n"
"var st=['UNUSED','READY','RUN','BLOCK','ZOMBIE'][p.state]||'?';\n"
"var c=p.state===2?'var(--green)':p.state===4?'var(--red)':'var(--fg)';\n"
"tb.innerHTML+='<tr><td>'+p.pid+'</td><td>'+esc(p.name)+'</td><td style=\"color:'+c+'\">'+st+'</td></tr>'})});\n"

"apiSend({cmd:'debug',type:'memory'},function(d){\n"
"if(!d.total_pages)return;\n"
"document.getElementById('d-meminfo').textContent=d.used_pages+' / '+d.total_pages+' pages ('+Math.round(d.used_pages*4)+' KB / '+Math.round(d.total_pages*4)+' KB)';\n"
"var g=document.getElementById('d-memgrid');g.innerHTML='';\n"
"var step=Math.max(1,Math.floor(d.total_pages/1024));\n"
"var bm=d.bitmap||'';\n"
"for(var i=0;i<1024&&i*step<d.total_pages;i++){\n"
"var used=bm.charAt(i)==='1';\n"
"var c=document.createElement('div');c.className='memcell';\n"
"c.style.background=used?'var(--accent)':'var(--bg4)';\n"
"c.title='Page '+(i*step)+(used?' (used)':' (free)');g.appendChild(c)}})}\n"

"function esc(s){return (s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}\n"

/* ============================================================ */
/* ---- TextEdit ---- */
/* ============================================================ */
"var edDirty=false,edFile='';\n"

"function editorOpen(path){\n"
"var p=path||document.getElementById('edit-path').value.trim();\n"
"if(!p){alert('Enter a file path first');return}\n"
"document.getElementById('edit-info').textContent='Opening...';\n"
"apiSend({cmd:'cat',path:p},function(d){\n"
"if(!d.ok){document.getElementById('edit-info').textContent='Open failed: '+(d.error||'unknown');return}\n"
"document.getElementById('editor').value=d.data||'';\n"
"document.getElementById('edit-path').value=p;\n"
"edFile=p;edDirty=false;edUpdStatus();\n"
"document.getElementById('editor-title').textContent='TextEdit \\u2014 '+p.split('/').pop();\n"
"openWin('editor')})}\n"

"function editorSave(){\n"
"var p=document.getElementById('edit-path').value.trim();\n"
"if(!p){alert('Enter a file path first');return}\n"
"var data=document.getElementById('editor').value;\n"
"document.getElementById('edit-info').textContent='Saving...';\n"
"apiSend({cmd:'write',path:p,data:data},function(d){\n"
"if(!d.ok){document.getElementById('edit-info').textContent='Save failed: '+(d.error||'unknown');return}\n"
"edFile=p;edDirty=false;edUpdStatus();\n"
"document.getElementById('edit-info').textContent='Saved \\u2713';\n"
"document.getElementById('editor-title').textContent='TextEdit \\u2014 '+p.split('/').pop();\n"
"refreshTree()})}\n"

"function editorNew(){\n"
"document.getElementById('editor').value='';\n"
"document.getElementById('edit-path').value='';\n"
"edFile='';edDirty=false;edUpdStatus();\n"
"document.getElementById('editor-title').textContent='TextEdit — Untitled'}\n"

"function edUpdStatus(){\n"
"document.getElementById('edit-dirty').textContent=edDirty?'Modified':'';\n"
"var v=document.getElementById('editor').value;\n"
"var lines=v?v.split('\\n').length:0;\n"
"var chars=v?v.length:0;\n"
"document.getElementById('edit-info').textContent=lines+' lines, '+chars+' chars'}\n"

"document.getElementById('editor').addEventListener('input',function(){edDirty=true;edUpdStatus()});\n"

"document.getElementById('editor').addEventListener('keydown',function(e){\n"
"if(e.key==='Tab'){e.preventDefault();\n"
"var s=this.selectionStart,en=this.selectionEnd;\n"
"this.value=this.value.substring(0,s)+'    '+this.value.substring(en);\n"
"this.selectionStart=this.selectionEnd=s+4}\n"
"if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();editorSave()}});\n"

/* ============================================================ */
/* ---- Init ---- */
/* ============================================================ */
"initTheme();\n"
"startBootScreen();\n"
"newTerm();\n"
"apiConnect();\n"
"updDock();\n"
"setInterval(refreshDash,3000);\n"

/* position monitor window to right side */
"(function(){\n"
"var mw=document.getElementById('win-monitor');\n"
"if(mw){var dw=document.getElementById('desktop').offsetWidth;\n"
"mw.style.left=(dw-400)+'px';mw.style.removeProperty('right')}\n"
"})();\n"

"</script>\n"
"</body>\n"
"</html>\n";

#endif /* WEB_PAGE_H */
